[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.38"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/jacksontj/lane"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
