# TODO: server connect info (now local only)
consul:
  service_name: consul_service_name

# TODO: region/auth/etc
aws:
  target_group_arn: arn:aws:elasticloadbalancing:region:more/etc

# TODO: mode-- addonly, sync
syncer:
  remove_delay: 20s
  lock_options:
    key: service/lockname/leader
    ttl: 10s
